version: '3.8'

services:
  web:
    container_name: trade_web
    image: trade_web
    build:
      context: .
      target: builder
      dockerfile: ./docker/Dockerfile
    stop_signal: SIGINT
    expose:
      - '5050'
    depends_on:
      - postgresql
      - queue
    volumes:
      - ./src:/src

  nginx:
    container_name: trade_nginx
    restart: always
    image: nginx:latest
    ports:
      - '80:8080'
    volumes:
      - ./src:/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgresql:
    container_name: trade_db
    restart: always
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  queue:
    container_name: trade_queue
    restart: always
    image: rabbitmq:3.12.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'

  worker:
    container_name: trade_worker
    image: trade_web
    command: celery --app src.infrastructure.queue.worker.queue_app worker --loglevel=info
    volumes:
      - ./src:/src
    restart: always
    depends_on:
      - web
      - queue

  scheduler:
    container_name: trade_scheduler
    image: trade_web
    command: python3 -m src.scheduler
    volumes:
      - ./src:/src
    restart: always
    depends_on:
      - web
      - worker


volumes:
  postgresql:
  rabbitmq:
