"""empty message

Revision ID: fb68ea72f9d2
Revises: 457f012e5e15
Create Date: 2023-12-26 17:38:02.224937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb68ea72f9d2'
down_revision: Union[str, None] = '457f012e5e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('buy_price', sa.Float(), nullable=False))
    op.add_column('order', sa.Column('sell_price', sa.Float(), nullable=False))
    op.drop_column('order', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('order', 'sell_price')
    op.drop_column('order', 'buy_price')
    # ### end Alembic commands ###
